//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobranzas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionCliente
    {
        public Nullable<int> usuarioID { get; set; }
        public int asignacionclienteID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaAsignacion { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
