//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobranzas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlPago
    {
        public Nullable<System.DateTime> fecha { get; set; }
        public string estado { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha_prox { get; set; }
        public int controlPagoID { get; set; }
        public Nullable<int> cobradorID { get; set; }
        public Nullable<int> cuotasID { get; set; }
    
        public virtual cuota cuota { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
