//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobranzas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotaVenta()
        {
            this.DetalleVentas = new HashSet<DetalleVenta>();
            this.planPagoes = new HashSet<planPago>();
        }
    
        public Nullable<System.DateTime> fecha { get; set; }
        public string nombre { get; set; }
        public Nullable<int> nit { get; set; }
        public Nullable<double> total { get; set; }
        public int notaVentaID { get; set; }
        public Nullable<int> clienteID { get; set; }
        public Nullable<int> vendedorID { get; set; }
        public Nullable<double> cuotainicial { get; set; }
        public Nullable<int> cantidadcouta { get; set; }
        public Nullable<bool> formapago { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVentas { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<planPago> planPagoes { get; set; }
    }
}
