//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobranzas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacionCobro
    {
        public Nullable<double> latitud { get; set; }
        public Nullable<double> longitud { get; set; }
        public string descripcion { get; set; }
        public int ubicacionCobroID { get; set; }
        public Nullable<int> clienteID { get; set; }
    
        public virtual cliente cliente { get; set; }
    }
}
