//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cobranzas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.AsignacionClientes = new HashSet<AsignacionCliente>();
            this.controlPagoes = new HashSet<controlPago>();
            this.NotaVentas = new HashSet<NotaVenta>();
            this.Seguimientoes = new HashSet<Seguimiento>();
            this.Perfils = new HashSet<Perfil>();
            this.Permisoes = new HashSet<Permiso>();
        }
    
        public string UsuarioNombre { get; set; }
        public string UsuarioApellido1 { get; set; }
        public string UsuarioApellido2 { get; set; }
        public string UsuarioEmail { get; set; }
        public string UsuarioTelefono { get; set; }
        public string UsuarioLogin { get; set; }
        public string UsuarioContrasena { get; set; }
        public Nullable<bool> UsuarioHabilitado { get; set; }
        public Nullable<bool> UsuarioEsSuperAdmin { get; set; }
        public Nullable<bool> UsuarioCambiarContrasena { get; set; }
        public int UsuarioID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionCliente> AsignacionClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<controlPago> controlPagoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotaVenta> NotaVentas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimiento> Seguimientoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perfil> Perfils { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Permiso> Permisoes { get; set; }
    }
}
